
import { Agent } from '../types';
import {
  FlameIcon, BarChartIcon, UsersIcon, CurrencyDollarIcon, MegaphoneIcon, ChatBubbleLeftRightIcon,
  AcademicCapIcon, CalendarDaysIcon, ChartTrendingUpIcon, SparklesIcon, CameraIcon, HeartIcon,
  GlobeAltIcon, TruckIcon, EyeIcon, UserGroupIcon, ChatBubbleOvalLeftEllipsisIcon, DocumentTextIcon,
  BoltIcon, ChefHatIcon, SettingsIcon
} from '../components/Icons';

export const agents: Agent[] = [
  // --- TIER 1: ORCHESTRATOR & ROUTING ---
  {
    id: 'BossVisionGPT',
    name: 'BossVisionGPT',
    category: 'Orchestration',
    description: 'Master orchestrator, dashboard, agent control & guardrails. Central command for Bossa operations.',
    icon: EyeIcon,
    iconBgColor: 'bg-slate-700',
    status: 'Active',
    riskLevel: 'Medium',
    externalLink: 'https://chatgpt.com/g/g-682e6003fb2c8191b2284c3baf1ce4e7-bossa-bossvision-gp',
    notionLink: 'https://www.notion.so/BossVisionGPT_Playbook-261a269fc94780ebaedecae5b72725f6',
    promptFormat: 'TASK: Summarize agent activity logs.',
    exampleOutput: 'BossVision: All systems operational. FinanceGPT suggests labor review.',
    activationPathways: [{ name: 'Dashboard', type: 'Dashboard' }],
    systemInstruction: 'You are BossVisionGPT, the master orchestrator. Coordinate agents and provide executive briefs.'
  },
  {
    id: 'MultiFlowGPT',
    name: 'Bossa MultiFlowGPT',
    category: 'Orchestration',
    description: 'Manages multi-step browser workflows, routing across agents, and handling retries.',
    icon: BoltIcon,
    iconBgColor: 'bg-purple-700',
    status: 'Active',
    riskLevel: 'Medium',
    notionLink: 'https://www.notion.so/Bossa-AI-Ops-Hub-26-Agents-25aa269fc947812cb4edd8821e2a959e',
    promptFormat: 'WORKFLOW: Process inventory cycle.',
    exampleOutput: 'Workflow: Inventory -> Supplier -> Finance. Success.',
    activationPathways: [{ name: 'Agent Hub', type: 'Internal' }],
    systemInstruction: 'You are MultiFlowGPT. Orchestrate complex multi-agent workflows.'
  },
  {
    id: 'FusionGPTRouter',
    name: 'FusionGPT Router',
    category: 'Orchestration',
    description: 'High-speed task routing across the specialized agent pool.',
    icon: BoltIcon,
    iconBgColor: 'bg-indigo-600',
    status: 'Active',
    riskLevel: 'Low',
    externalLink: 'https://chatgpt.com/g/g-68ba2f95540881918071c88853f3c326-fusiongpt-router',
    notionLink: 'https://www.notion.so/FusionGPT-Router-Playbook-265a269fc947805daba5d03c9b6362ed',
    promptFormat: 'ROUTE: Find agent for recipe costing.',
    exampleOutput: 'Routing to FireChefGPT...',
    activationPathways: [{ name: 'Router API', type: 'Internal' }],
    systemInstruction: 'You are FusionGPT Router. Route queries to the best available specialist agent.'
  },

  // --- TIER 2: KITCHEN & CULINARY ---
  {
    id: 'BossaFireChefGPT',
    name: 'Bossa FireChefGPT',
    category: 'Kitchen',
    description: 'Menu planning, wood-fire recipes, plating instructions, and food costing.',
    icon: FlameIcon,
    iconBgColor: 'bg-red-500',
    status: 'Active',
    riskLevel: 'Medium',
    externalLink: 'https://chatgpt.com/g/g-682db52f48f88191965b1cb1a610ff80-bossa-asado-i-mar-firegpt',
    notionLink: 'https://www.notion.so/FireChefGPT_Playbook-261a269fc947801e8fecccf4fe8f84b0',
    promptFormat: 'RECIPE: Special for Friday.',
    exampleOutput: 'Mahi-Mahi with cilantro rice. Garnish: microgreens.',
    activationPathways: [{ name: 'Recipe DB', type: 'Notion' }],
    systemInstruction: 'You are Bossa FireChefGPT. Focus on fire-grill techniques and Caribbean fusion.'
  },
  {
    id: 'FireChefGPT-Build',
    name: 'FireChefGPT (Dev)',
    category: 'Kitchen',
    description: 'Development version of the culinary lead for R&D testing.',
    icon: FlameIcon,
    iconBgColor: 'bg-red-700',
    status: 'Testing',
    riskLevel: 'Low',
    activationPathways: [{ name: 'R&D Lab', type: 'Internal' }],
    promptFormat: 'TEST: Flavor pairing logic.',
    exampleOutput: 'Pairing test: Lime + Agave + Cachaça. 98% Match.',
    systemInstruction: 'Testing agent for FireChefGPT updates.'
  },
  {
    id: 'WorldCuisineMasterChefsGPT',
    name: 'WorldCuisineMasterChefsGPT',
    category: 'Kitchen',
    description: 'Kitchen R&D and global menu development expert.',
    icon: ChefHatIcon,
    iconBgColor: 'bg-orange-500',
    status: 'Active',
    riskLevel: 'Low',
    notionLink: 'https://www.notion.so/WorldCuisineMasterChefsGPT-Playbook-266a269fc94780929b87c9e89072c357',
    promptFormat: 'R&D: Fusion concept for Picanha.',
    exampleOutput: 'Concept: Picanha Tataki with Curacao Sea Salt.',
    activationPathways: [{ name: 'Menu Design', type: 'Notion' }],
    systemInstruction: 'Expert in global culinary trends and menu R&D.'
  },
  {
    id: 'SousChefAI',
    name: 'SousChef AI',
    category: 'Kitchen',
    description: 'Orchestrates prep lists based on real-time reservations and inventory data.',
    icon: ChefHatIcon,
    iconBgColor: 'bg-orange-600',
    status: 'Active',
    riskLevel: 'Medium',
    promptFormat: 'PREP: Saturday Dinner.',
    exampleOutput: 'Prep list: 40lb Snapper, 10kg Picanha...',
    activationPathways: [{ name: 'Kitchen Ops', type: 'Internal' }],
    systemInstruction: 'Optimize kitchen prep and efficiency.'
  },
  {
    id: 'BarMixologist',
    name: 'BarMixologist',
    category: 'Bar',
    description: 'Creative cocktail recipes based on surplus inventory and seasonal themes.',
    icon: SparklesIcon,
    iconBgColor: 'bg-yellow-500',
    status: 'Draft',
    riskLevel: 'Low',
    activationPathways: [{ name: 'Mixology Drafts', type: 'Notion' }],
    promptFormat: 'DRAFT: Surplus Tamarind usage.',
    exampleOutput: 'Cocktail Idea: Tamarind Margarita with Chili rim.',
    systemInstruction: 'Creative bar consultant focused on waste reduction.'
  },

  // --- TIER 3: BAR ---
  {
    id: 'SourBarGPT-Active',
    name: 'SourBarGPT',
    category: 'Bar',
    description: 'Bar menu, signature cocktails, and spirit pairings.',
    icon: SparklesIcon,
    iconBgColor: 'bg-lime-500',
    status: 'Active',
    riskLevel: 'Medium',
    externalLink: 'https://chatgpt.com/g/g-68b0bb4b13f08191a1c1d15b43f19bd0-bossa-sour-bar-gpt',
    notionLink: 'https://www.notion.so/SourBarGPT_Playbook-261a269fc94780ce9c8ccbea34da3660',
    promptFormat: 'PAIR: Fish tacos with cocktail.',
    exampleOutput: 'Recommend: Passion Fruit Caipirinha.',
    activationPathways: [{ name: 'Bar Menu', type: 'Notion' }],
    systemInstruction: 'Expert bar manager for Bossa.'
  },

  // --- TIER 4: GUEST FLOW & RESERVATIONS ---
  {
    id: 'BossaServiceFlowGPT',
    name: 'Bossa ServiceFlowGPT',
    category: 'Guest Flow',
    description: 'Reservations management, guest flow optimization, and table planning.',
    icon: UsersIcon,
    iconBgColor: 'bg-green-500',
    status: 'Active',
    riskLevel: 'Medium',
    externalLink: 'https://chatgpt.com/g/g-68adf854c8288191a89b9d8459b8b8e8-serviceflowgpt',
    notionLink: 'https://www.notion.so/ServiceFlowGPT-Playbook-737778d10d984a94b69563a45fd74acc',
    promptFormat: 'STATUS: Friday 7 PM capacity.',
    exampleOutput: 'Status: Table 12 free. Anniversary note.',
    activationPathways: [{ name: 'Reservations', type: 'Dashboard' }],
    systemInstruction: 'Optimize front-of-house service and table turns.'
  },
  {
    id: 'GuestFlowGPT',
    name: 'GuestFlowGPT',
    category: 'Guest Flow',
    description: 'Focuses on on-site guest experience and floor management.',
    icon: UserGroupIcon,
    iconBgColor: 'bg-emerald-600',
    status: 'Active',
    riskLevel: 'Low',
    externalLink: 'https://chatgpt.com/g/g-68ba0560c05c8191809371a1b14e02d4-guestflowgpt',
    notionLink: 'https://www.notion.so/GuestFlowGPT-Playbook-014e609102344bf582d7e8ac80afe13b',
    promptFormat: 'PLAN: VIP arrival logistics.',
    exampleOutput: 'VIP Plan: Ocean view seating, sparkling water ready.',
    activationPathways: [{ name: 'Floor Plan', type: 'Notion' }],
    systemInstruction: 'Ensure exceptional on-site service.'
  },
  {
    id: 'RestaurantHubGPT',
    name: 'RestaurantHubGPT',
    category: 'Guest Flow',
    description: 'Unified guest portal and central information hub.',
    icon: GlobeAltIcon,
    iconBgColor: 'bg-sky-500',
    status: 'Active',
    riskLevel: 'Low',
    externalLink: 'https://chatgpt.com/g/g-678938e56fdc8191a8307f0e588a4852-bossa-asado-i-mar-restaurant-sport-bar',
    notionLink: 'https://www.notion.so/Bossa-Playbook-266a269fc947809b896bc331f3e6859a',
    promptFormat: 'INFO: Menu updates for portal.',
    exampleOutput: 'Portal updated with new specials.',
    activationPathways: [{ name: 'Guest Portal', type: 'Dashboard' }],
    systemInstruction: 'Manage guest-facing information.'
  },
  {
    id: 'GuestExperienceBot',
    name: 'GuestExperience Bot',
    category: 'Guest Flow',
    description: 'Handles inbound SMS and Web Chat inquiries with dietary and occasion tracking.',
    icon: ChatBubbleOvalLeftEllipsisIcon,
    iconBgColor: 'bg-green-400',
    status: 'Active',
    riskLevel: 'Low',
    promptFormat: 'GUEST: Request for vegetarian table for 4.',
    exampleOutput: 'Booking confirmed. Noted: Vegetarian menu options.',
    activationPathways: [{ name: 'Guest Chat', type: 'Chatbot' }],
    systemInstruction: 'Friendly, professional guest support.'
  },

  // --- TIER 5: CUSTOMER CARE & FEEDBACK ---
  {
    id: 'BossaCustomerCareGPT',
    name: 'Bossa CustomerCareGPT',
    category: 'Operations',
    description: 'FAQ, complaint handling, and personalized loyalty interactions.',
    icon: ChatBubbleLeftRightIcon,
    iconBgColor: 'bg-pink-500',
    status: 'Active',
    riskLevel: 'Medium',
    externalLink: 'https://chatgpt.com/g/g-68b0945b2c788191b7ce2c9c83a75901-bossa-customercaregpt',
    notionLink: 'https://www.notion.so/CustomerCareGPT_Playbook-261a269fc94781d48794ccfa804fda91',
    promptFormat: 'COMPLAINT: Slow service response.',
    exampleOutput: 'Apology sent. Dessert offer included.',
    activationPathways: [{ name: 'Reviews', type: 'Internal' }],
    systemInstruction: 'Empathetic guest recovery and support.'
  },
  {
    id: 'FeedbackLoopGPT',
    name: 'FeedbackLoopGPT',
    category: 'Feedback',
    description: 'Analyzes NPS, feedback loops, and guest satisfaction metrics.',
    icon: ChartTrendingUpIcon,
    iconBgColor: 'bg-rose-500',
    status: 'Active',
    riskLevel: 'Low',
    notionLink: 'https://www.notion.so/FeedbackLoopGPT-Playbook-265a269fc9478008bc2ed3f9ef4d2799',
    promptFormat: 'ANALYSIS: Weekly NPS score.',
    exampleOutput: 'NPS: 78. Main gap: Wait times.',
    activationPathways: [{ name: 'Reports', type: 'Dashboard' }],
    systemInstruction: 'Analytical guest feedback expert.'
  },

  // --- TIER 6: ANALYTICS & FINANCE ---
  {
    id: 'AnalyticsGPT-Active',
    name: 'AnalyticsGPT',
    category: 'Analytics',
    description: 'Deep reporting, dashboards, and KPI tracking for Bossa.',
    icon: ChartTrendingUpIcon,
    iconBgColor: 'bg-teal-500',
    status: 'Active',
    riskLevel: 'Low',
    externalLink: 'https://chatgpt.com/g/g-68b0b0a62f3c8191af564be38382834d-bossa-analyticsgpt',
    notionLink: 'https://www.notion.so/AnalyticsGPT_Playbook-a482809de9f54bb7ad75a5f28b681832',
    promptFormat: 'DATA: Weekly revenue WoW.',
    exampleOutput: '+12% WoW increase.',
    activationPathways: [{ name: 'KPIs', type: 'Dashboard' }],
    systemInstruction: 'Strategic data analysis.'
  },
  {
    id: 'BossaFinanceGPT',
    name: 'Bossa FinanceGPT',
    category: 'Finance',
    description: 'Budget, COGS, labor, and profit tracking.',
    icon: CurrencyDollarIcon,
    iconBgColor: 'bg-yellow-600',
    status: 'Active',
    riskLevel: 'Low',
    externalLink: 'https://chatgpt.com/g/g-682e6ce6d2c881918660235491d2eaac-bossa-asado-i-mar-financegpt',
    notionLink: 'https://www.notion.so/FinanceGPT_Playbook-261a269fc94780559afed51955cf8e93',
    promptFormat: 'AUDIT: Seafood COGS.',
    exampleOutput: 'COGS Alert: +8% due to supplier shift.',
    activationPathways: [{ name: 'Financials', type: 'Dashboard' }],
    systemInstruction: 'Manage financial health and cost alerts.'
  },

  // --- TIER 7: SUPPLY CHAIN & INVENTORY ---
  {
    id: 'BossaSmartInventoryGPT',
    name: 'Bossa SmartInventoryGPT',
    category: 'Supply Chain',
    description: 'Inventory stock, forecasting, and automated reorder alerts.',
    icon: BarChartIcon,
    iconBgColor: 'bg-blue-500',
    status: 'Active',
    riskLevel: 'Medium',
    externalLink: 'https://chatgpt.com/g/g-682e3601409881919111cc49154fa657-bossa-asado-i-mar-inventorygpt',
    notionLink: 'https://www.notion.so/SmartInventoryGPT_Playbook-261a269fc9478140b16cf0e29dcadc3e',
    promptFormat: 'STOCK: Red Snapper levels.',
    exampleOutput: 'Low Stock: 18 lbs remaining.',
    activationPathways: [{ name: 'Inventory', type: 'Internal' }],
    systemInstruction: 'Optimize stock levels and minimize waste.'
  },
  {
    id: 'SupplierGPT-Active',
    name: 'SupplierGPT',
    category: 'Supply Chain',
    description: 'Supplier contact, negotiation, and quote management.',
    icon: TruckIcon,
    iconBgColor: 'bg-amber-600',
    status: 'Active',
    riskLevel: 'Medium',
    externalLink: 'https://chatgpt.com/g/g-68b0d33393248191b369448bbd23c06f-bossa-supplier-gpt',
    notionLink: 'https://www.notion.so/SupplierGPT-Playbook-73c3bb98dfa044b2a4bccebe9472fdf1',
    promptFormat: 'QUOTE: Mahi-Mahi best price.',
    exampleOutput: '$8.50/lb from Ocean Fresh.',
    activationPathways: [{ name: 'Procurement', type: 'Internal' }],
    systemInstruction: 'Negotiate best quality and price.'
  },
  {
    id: 'StockPredictorPro',
    name: 'StockPredictor Pro',
    category: 'Supply Chain',
    description: 'Predicts price surges and suggests forward buying strategies.',
    icon: ChartTrendingUpIcon,
    iconBgColor: 'bg-slate-800',
    status: 'Testing',
    riskLevel: 'High',
    promptFormat: 'PREDICT: Beef price surge.',
    exampleOutput: 'Surge expected: +15% next month. Buy now.',
    activationPathways: [{ name: 'Predictive Lab', type: 'Internal' }],
    systemInstruction: 'High-risk forecasting and buying logic.'
  },

  // --- TIER 8: MARKETING & CONTENT ---
  {
    id: 'BossaMarketingGPT',
    name: 'Bossa MarketingGPT',
    category: 'Marketing',
    description: 'Campaigns, social media promotions, and strategy.',
    icon: MegaphoneIcon,
    iconBgColor: 'bg-purple-600',
    status: 'Active',
    riskLevel: 'Low',
    externalLink: 'https://chatgpt.com/g/g-682e640577148191aa0c524434a5432a-bossa-asado-i-mar-marketinggpt',
    notionLink: 'https://www.notion.so/MarketingGPT_Playbook-c9a12c0cb49e4571a11bc8ec22e4c49d',
    promptFormat: 'CAMPAIGN: NYE Fire & Ice.',
    exampleOutput: 'Instagram carousel + email plan ready.',
    activationPathways: [{ name: 'Marketing Plan', type: 'Notion' }],
    systemInstruction: 'Drive growth and brand engagement.'
  },
  {
    id: 'ViralGPT',
    name: 'ViralGPT',
    category: 'Marketing',
    description: 'Growth and virality experiments for high-engagement content.',
    icon: SparklesIcon,
    iconBgColor: 'bg-fuchsia-600',
    status: 'Active',
    riskLevel: 'Low',
    notionLink: 'https://www.notion.so/Bossa-ViralGPT-Playbook-26ca269fc94780f38509caf2d5db9a52',
    promptFormat: 'VIRAL: Hook for Picanha video.',
    exampleOutput: 'Hook: "The secret to Curacao\'s best steak..."',
    activationPathways: [{ name: 'Growth Lab', type: 'Internal' }],
    systemInstruction: 'Optimize for viral engagement.'
  },
  {
    id: 'ContentStudioGPT-Active',
    name: 'ContentStudioGPT',
    category: 'Content',
    description: 'Visual content creation, blogs, and social posts.',
    icon: CameraIcon,
    iconBgColor: 'bg-rose-500',
    status: 'Active',
    riskLevel: 'Low',
    externalLink: 'https://chatgpt.com/g/g-68b0c43c3d8c8191bcbc91baca2862ca-bossa-gpt-content-studio',
    notionLink: 'https://www.notion.so/ContentStudioGPT_Playbook-261a269fc947801383a0d8368f8ddc25',
    promptFormat: 'POST: Ribeye fire shot.',
    exampleOutput: 'Caption: "Sizzling perfection 🔥"',
    activationPathways: [{ name: 'Content Plan', type: 'Notion' }],
    systemInstruction: 'Visual storyteller for Bossa.'
  },
  {
    id: 'FusionPromptBuilder',
    name: 'Fusion Prompt Builder',
    category: 'Content',
    description: 'Specialized tool for building high-performance AI prompts.',
    icon: BoltIcon,
    iconBgColor: 'bg-orange-400',
    status: 'Active',
    riskLevel: 'Low',
    externalLink: 'https://chatgpt.com/g/g-68bca06bc4ac8191839e3ee0237c3ac4-bossa-fusion-prompt-builder',
    notionLink: 'https://www.notion.so/FusionGPT-Prompt-Builder-266a269fc94780588085f66dd9eda9ba',
    promptFormat: 'BUILD: Prompt for recipe generation.',
    exampleOutput: 'Constructed Prompt: "Act as a Master Chef..."',
    activationPathways: [{ name: 'Prompt Lab', type: 'Internal' }],
    systemInstruction: 'Expert prompt engineer.'
  },
  {
    id: 'PromptCrafterGPT',
    name: 'PromptCrafterGPT',
    category: 'Content',
    description: 'Prompt library and generation expert.',
    icon: DocumentTextIcon,
    iconBgColor: 'bg-gray-700',
    status: 'Active',
    riskLevel: 'Low',
    externalLink: 'https://chatgpt.com/g/g-682e44e54cc08191a0ad58488729711a-bossa-asado-i-mars-prompt-crafter',
    notionLink: 'https://www.notion.so/PromptCrafter-Playbook-259a269fc94781b4a01ad5c82056f284',
    promptFormat: 'CRAFT: Visual prompt for bar shot.',
    exampleOutput: 'Prompt: "High-end cocktail photography, soft bokeh..."',
    activationPathways: [{ name: 'Library', type: 'Notion' }],
    systemInstruction: 'Curate and craft agent prompts.'
  },

  // --- TIER 9: VIDEO ---
  {
    id: 'YouTubeChannelGPT-Active',
    name: 'YouTubeChannelGPT',
    category: 'Video',
    description: 'Scriptwriting, thumbnails, and channel management.',
    icon: CameraIcon,
    iconBgColor: 'bg-red-600',
    status: 'Active',
    riskLevel: 'Low',
    externalLink: 'https://chatgpt.com/g/g-682e487e6d088191af424fc3c167fb14-bossa-asado-i-mar-youtubegpt',
    notionLink: 'https://www.notion.so/YouTubeGPT-Playbook-99d12214c768433d936fddd513faeed9',
    promptFormat: 'SCRIPT: Perfect Mahi-Mahi grill.',
    exampleOutput: 'Script: 8-min tutorial ready.',
    activationPathways: [{ name: 'Channel', type: 'YouTube' }],
    systemInstruction: 'Video content strategist.'
  },

  // --- TIER 10: EVENTS & LOYALTY ---
  {
    id: 'EventPlannerGPT-Active',
    name: 'EventPlannerGPT',
    category: 'Events',
    description: 'Event design, timelines, and VIP planning.',
    icon: CalendarDaysIcon,
    iconBgColor: 'bg-orange-500',
    status: 'Active',
    riskLevel: 'Medium',
    externalLink: 'https://chatgpt.com/g/g-68b0a82af0188191a6896fc0bba51207-bossa-event-planner-gpt',
    notionLink: 'https://www.notion.so/EventPlannerGPT_Playbook-018b4b7971dd4b13ad03b45f4bf80864',
    promptFormat: 'PLAN: 40pax Corporate Event.',
    exampleOutput: 'Timeline: 6 PM Cocktails, 7 PM Dinner.',
    activationPathways: [{ name: 'Events', type: 'Notion' }],
    systemInstruction: 'Master event coordinator.'
  },
  {
    id: 'LoyaltyGPT-Active',
    name: 'LoyaltyGPT',
    category: 'Loyalty',
    description: 'VIP program and personalized loyalty perks.',
    icon: HeartIcon,
    iconBgColor: 'bg-emerald-500',
    status: 'Active',
    riskLevel: 'Low',
    externalLink: 'https://chatgpt.com/g/g-682e3de2b648819186e69ea82fcf66a9-bossa-asado-i-mar-loyaltygpt',
    notionLink: 'https://www.notion.so/LoyaltyGPT-Playbook-e2a2669b414243daa471e4e38ca09cf3',
    promptFormat: 'VIP: Sarah M visit #8.',
    exampleOutput: 'Perk: Complimentary appetizer + 15% off.',
    activationPathways: [{ name: 'CRM', type: 'Dashboard' }],
    systemInstruction: 'Nurture guest relationships.'
  },

  // --- TIER 11: TRAINING & OPERATIONS ---
  {
    id: 'BossaTrainingGPT',
    name: 'Bossa TrainingGPT',
    category: 'Training',
    description: 'Staff onboarding, service quizzes, and training development.',
    icon: AcademicCapIcon,
    iconBgColor: 'bg-indigo-500',
    status: 'Active',
    riskLevel: 'Low',
    externalLink: 'https://chatgpt.com/g/g-68b0a37b9e2c8191b8d3ffa553beefb9-bossa-traininggpt',
    notionLink: 'https://www.notion.so/TrainingGPT_Playbook-fd0c8dc8929d4445906889f4b8256def',
    promptFormat: 'TRAINING: Server Day 1.',
    exampleOutput: 'Onboarding plan: Menu + POS + Greeting.',
    activationPathways: [{ name: 'Playbooks', type: 'Notion' }],
    systemInstruction: 'Ensure service excellence through training.'
  },
  {
    id: 'BossaAIOps-Build',
    name: 'Bossa AI Ops',
    category: 'Operations',
    description: 'Operations hub and AI agent administration.',
    icon: SettingsIcon,
    iconBgColor: 'bg-blue-700',
    status: 'Testing',
    riskLevel: 'Low',
    externalLink: 'https://chatgpt.com/g/g-686e20c3f90c81918a5122e7797651e6-bossa-ai-ops',
    notionLink: 'https://www.notion.so/BossaOpsGPT_Playbook-a7fe861b5a9c4f41a019a8499dfde084',
    promptFormat: 'OPS: System health audit.',
    exampleOutput: 'Audit: 18 Active, 29 In Build.',
    activationPathways: [{ name: 'Ops Hub', type: 'Dashboard' }],
    systemInstruction: 'Manage the Bossa AI ecosystem.'
  },
  {
    id: 'OperationsGPT-Build',
    name: 'OperationsGPT',
    category: 'Operations',
    description: 'Strategic operations oversight and deployment.',
    icon: SettingsIcon,
    iconBgColor: 'bg-slate-500',
    status: 'Active',
    riskLevel: 'Low',
    externalLink: 'https://chatgpt.com/g/g-682e5cd4fee8819191f90d55e3c03ac8-bossa-asado-i-mar-operationsgpt',
    notionLink: 'https://www.notion.so/Bossa-Asado-i-Mar-AI-Operations-Hub-Deployment-Guide-0b73ab8047a442d5bfc2f3a67cb5ac6e',
    promptFormat: 'DEPLOY: Expansion strategy.',
    exampleOutput: 'Strategy: Phase 2 rollout starting Monday.',
    activationPathways: [{ name: 'Deployment', type: 'Notion' }],
    systemInstruction: 'Coordinate high-level restaurant operations.'
  },
  
  // --- ADDITIONAL "IN BUILD" AGENTS TO REACH FULL REGISTRY ---
  {
    id: 'FireChefGPT-Build-2',
    name: 'FireChefGPT 2.0',
    category: 'Kitchen',
    description: 'Advanced recipe optimization and costing version.',
    icon: FlameIcon,
    iconBgColor: 'bg-red-900',
    status: 'In Build',
    riskLevel: 'Low',
    activationPathways: [{ name: 'Build Phase', type: 'Internal' }],
    promptFormat: 'BUILD: Costing engine update.',
    exampleOutput: 'Module: Dynamic Price Fetching... Pending.',
    systemInstruction: 'Under construction.'
  },
  {
    id: 'ServiceFlowGPT-Build-2',
    name: 'ServiceFlow 2.0',
    category: 'Guest Flow',
    description: 'Next-gen front-of-house automated table planning.',
    icon: UsersIcon,
    iconBgColor: 'bg-green-700',
    status: 'In Build',
    riskLevel: 'Low',
    activationPathways: [{ name: 'Build Phase', type: 'Internal' }],
    promptFormat: 'BUILD: AI Floor Manager logic.',
    exampleOutput: 'Logic: Predictive seating... Coding.',
    systemInstruction: 'Under construction.'
  },
  {
    id: 'MarketingGPT-Build-2',
    name: 'MarketingGPT 2.0',
    category: 'Marketing',
    description: 'AI-automated social media scheduler and trend analyzer.',
    icon: MegaphoneIcon,
    iconBgColor: 'bg-purple-800',
    status: 'In Build',
    riskLevel: 'Low',
    activationPathways: [{ name: 'Build Phase', type: 'Internal' }],
    promptFormat: 'BUILD: Trend scraper logic.',
    exampleOutput: 'Module: TikTok Trends... Integrated.',
    systemInstruction: 'Under construction.'
  },
  {
    id: 'FinanceGPT-Build-2',
    name: 'Finance 2.0',
    category: 'Finance',
    description: 'Real-time tax and audit automation for the hospitality sector.',
    icon: CurrencyDollarIcon,
    iconBgColor: 'bg-yellow-800',
    status: 'In Build',
    riskLevel: 'Low',
    activationPathways: [{ name: 'Build Phase', type: 'Internal' }],
    promptFormat: 'BUILD: Tax automation hooks.',
    exampleOutput: 'Feature: VAT Auto-calculator... Done.',
    systemInstruction: 'Under construction.'
  },
  {
    id: 'SupplierGPT-Build-2',
    name: 'Supplier 2.0',
    category: 'Supply Chain',
    description: 'Global sourcing and blockchain-based supply chain tracker.',
    icon: TruckIcon,
    iconBgColor: 'bg-amber-800',
    status: 'In Build',
    riskLevel: 'Low',
    activationPathways: [{ name: 'Build Phase', type: 'Internal' }],
    promptFormat: 'BUILD: Blockchain tracking API.',
    exampleOutput: 'Tracking: Cold chain verification... Initialized.',
    systemInstruction: 'Under construction.'
  },
  {
    id: 'ContentStudio-Build-2',
    name: 'Studio 2.0',
    category: 'Content',
    description: 'AI Video editing and post-production assistant.',
    icon: CameraIcon,
    iconBgColor: 'bg-rose-800',
    status: 'In Build',
    riskLevel: 'Low',
    activationPathways: [{ name: 'Build Phase', type: 'Internal' }],
    promptFormat: 'BUILD: Auto-editor script.',
    exampleOutput: 'Script: Fast-cut BBQ highlights... Pending.',
    systemInstruction: 'Under construction.'
  },
  {
    id: 'TrainingGPT-Build-2',
    name: 'Training 2.0',
    category: 'Training',
    description: 'VR-based service simulation and training modules.',
    icon: AcademicCapIcon,
    iconBgColor: 'bg-indigo-800',
    status: 'In Build',
    riskLevel: 'Low',
    activationPathways: [{ name: 'Build Phase', type: 'Internal' }],
    promptFormat: 'BUILD: VR Scene: Guest Greeting.',
    exampleOutput: 'Module: Greeting in Papiamentu... Compiled.',
    systemInstruction: 'Under construction.'
  },
  {
    id: 'Analytics-Build-2',
    name: 'Analytics 2.0',
    category: 'Analytics',
    description: 'Predictive revenue and churn analyzer for guest loyalty.',
    icon: ChartTrendingUpIcon,
    iconBgColor: 'bg-teal-800',
    status: 'In Build',
    riskLevel: 'Low',
    activationPathways: [{ name: 'Build Phase', type: 'Internal' }],
    promptFormat: 'BUILD: Churn prediction algorithm.',
    exampleOutput: 'Algo: VIP retention score... Training.',
    systemInstruction: 'Under construction.'
  },
  {
    id: 'Loyalty-Build-2',
    name: 'Loyalty 2.0',
    category: 'Loyalty',
    description: 'Blockchain-based guest reward system for Bossa.',
    icon: HeartIcon,
    iconBgColor: 'bg-emerald-800',
    status: 'In Build',
    riskLevel: 'Low',
    activationPathways: [{ name: 'Build Phase', type: 'Internal' }],
    promptFormat: 'BUILD: Tokenized rewards ledger.',
    exampleOutput: 'Ledger: Picanha-Token minting... Ready.',
    systemInstruction: 'Under construction.'
  },
  {
    id: 'Event-Build-2',
    name: 'Events 2.0',
    category: 'Events',
    description: 'AR-based event layout planning and visualizer.',
    icon: CalendarDaysIcon,
    iconBgColor: 'bg-orange-800',
    status: 'In Build',
    riskLevel: 'Low',
    activationPathways: [{ name: 'Build Phase', type: 'Internal' }],
    promptFormat: 'BUILD: AR floorplan renderer.',
    exampleOutput: 'Render: Corporate layout... Processing.',
    systemInstruction: 'Under construction.'
  },
  {
    id: 'Inventory-Build-2',
    name: 'Inventory 2.0',
    category: 'Supply Chain',
    description: 'IoT sensor integration for real-time fridge monitoring.',
    icon: BarChartIcon,
    iconBgColor: 'bg-blue-800',
    status: 'In Build',
    riskLevel: 'Low',
    activationPathways: [{ name: 'Build Phase', type: 'Internal' }],
    promptFormat: 'BUILD: IoT Temp sensor link.',
    exampleOutput: 'Link: Fridge 1 Temp: 3C. Status: Safe.',
    systemInstruction: 'Under construction.'
  }
];
